# Generated by Django 5.0.6 on 2024-06-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=50)),
                ('paid_parking_around', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DaySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(1, 'friday'), (2, 'saturday'), (3, 'sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FB', 'football'), ('VB', 'volleyball'), ('HB', 'handball'), ('PP', 'ping-pong'), ('BB', 'basketball'), ('TN', 'tennis')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(2, '16:00'), (1, '13:00'), (3, '19:00')])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwishApp.court')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='intended_for',
            field=models.ManyToManyField(to='SwishApp.sport'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwishApp.court')),
                ('day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SwishApp.daysurvey')),
                ('time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SwishApp.timesurvey')),
            ],
        ),
    ]
