# Generated by Django 5.0.6 on 2024-06-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('free_parking_around', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Ping-pong', 'Ping-pong'), ('Handball', 'Handball'), ('Football', 'Football')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwishApp.court')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')])),
                ('time', models.IntegerField(choices=[(1, '13:00'), (2, '16:00'), (3, '19:00')])),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ManyToManyField(to='SwishApp.court')),
                ('sport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SwishApp.sport')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='court',
            name='intended_for',
            field=models.ManyToManyField(to='SwishApp.sport'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwishApp.match')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwishApp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='planned_matches',
            field=models.ManyToManyField(blank=True, through='SwishApp.UserProfileMatch', to='SwishApp.match'),
        ),
    ]
