# Generated by Django 5.0.6 on 2024-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(3, 'sunday'), (1, 'friday'), (2, 'saturday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('PP', 'ping-pong'), ('BB', 'basketball'), ('TN', 'tennis'), ('HB', 'handball'), ('FB', 'football'), ('VB', 'volleyball')], max_length=2),
        ),
    ]
