# Generated by Django 5.0.6 on 2024-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0002_alter_daysurvey_answer_alter_sport_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='localisation',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(1, 'friday'), (2, 'saturday'), (3, 'sunday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('BB', 'basketball'), ('HB', 'handball'), ('FB', 'football'), ('TN', 'tennis'), ('PP', 'ping-pong'), ('VB', 'volleyball')], max_length=2),
        ),
        migrations.AlterField(
            model_name='timesurvey',
            name='answer',
            field=models.IntegerField(choices=[(1, '13:00'), (2, '16:00'), (3, '19:00')]),
        ),
    ]
