# Generated by Django 5.0.6 on 2024-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0003_rename_localisation_court_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(1, 'friday'), (3, 'sunday'), (2, 'saturday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Handball', 'Handball'), ('Basketball', 'Basketball'), ('Ping-pong', 'Ping-pong'), ('Tennis', 'Tennis'), ('Football', 'Football'), ('Volleyball', 'Volleyball')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timesurvey',
            name='answer',
            field=models.IntegerField(choices=[(2, '16:00'), (1, '13:00'), (3, '19:00')]),
        ),
    ]
