# Generated by Django 5.0.6 on 2024-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0004_alter_daysurvey_answer_alter_sport_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='paid_parking_around',
            new_name='free_parking_around',
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Handball', 'Handball'), ('Ping-pong', 'Ping-pong')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timesurvey',
            name='answer',
            field=models.IntegerField(choices=[(1, '13:00'), (3, '19:00'), (2, '16:00')]),
        ),
    ]
