# Generated by Django 5.0.6 on 2024-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0006_alter_daysurvey_answer_alter_sport_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(3, 'sunday'), (2, 'saturday'), (1, 'friday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Ping-pong', 'Ping-pong'), ('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Handball', 'Handball'), ('Tennis', 'Tennis'), ('Basketball', 'Basketball')], max_length=20),
        ),
    ]
