# Generated by Django 5.0.6 on 2024-06-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0007_alter_daysurvey_answer_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(2, 'saturday'), (3, 'sunday'), (1, 'friday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Ping-pong', 'Ping-pong'), ('Handball', 'Handball'), ('Volleyball', 'Volleyball'), ('Football', 'Football')], max_length=20),
        ),
    ]
