# Generated by Django 5.0.6 on 2024-06-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0008_alter_daysurvey_answer_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(3, 'sunday'), (2, 'saturday'), (1, 'friday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Handball', 'Handball'), ('Tennis', 'Tennis'), ('Ping-pong', 'Ping-pong'), ('Basketball', 'Basketball')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timesurvey',
            name='answer',
            field=models.IntegerField(choices=[(1, '13:00'), (2, '16:00'), (3, '19:00')]),
        ),
    ]
