# Generated by Django 5.0.6 on 2024-06-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0010_alter_daysurvey_answer_alter_sport_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daysurvey',
            name='answer',
            field=models.IntegerField(choices=[(2, 'saturday'), (3, 'sunday'), (1, 'friday')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Basketball', 'Basketball'), ('Ping-pong', 'Ping-pong'), ('Tennis', 'Tennis'), ('Football', 'Football'), ('Handball', 'Handball')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timesurvey',
            name='answer',
            field=models.IntegerField(choices=[(1, '13:00'), (2, '16:00'), (3, '19:00')]),
        ),
    ]
