# Generated by Django 5.0.6 on 2024-06-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0011_match_added_by_alter_daysurvey_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (5, 'friday'), (4, 'thursday'), (7, 'sunday'), (6, 'saturday'), (3, 'wednesday')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.IntegerField(choices=[(1, '13:00'), (2, '16:00'), (3, '19:00')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Handball', 'Handball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis'), ('Ping-pong', 'Ping-pong'), ('Basketball', 'Basketball')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DaySurvey',
        ),
        migrations.DeleteModel(
            name='TimeSurvey',
        ),
    ]
