# Generated by Django 5.0.6 on 2024-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0012_alter_match_day_alter_match_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='court',
        ),
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.IntegerField(choices=[(7, 'sunday'), (6, 'saturday'), (4, 'thursday'), (5, 'friday'), (1, 'monday'), (2, 'tuesday'), (3, 'wednesday')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.IntegerField(choices=[(3, '19:00'), (1, '13:00'), (2, '16:00')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Handball', 'Handball'), ('Ping-pong', 'Ping-pong'), ('Football', 'Football'), ('Tennis', 'Tennis'), ('Basketball', 'Basketball')], max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ManyToManyField(to='SwishApp.court'),
        ),
    ]
