# Generated by Django 5.0.6 on 2024-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0013_remove_match_court_alter_match_day_alter_match_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.IntegerField(choices=[(1, '13:00'), (2, '16:00'), (3, '19:00')]),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Ping-pong', 'Ping-pong'), ('Handball', 'Handball'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Football', 'Football'), ('Volleyball', 'Volleyball')], max_length=20),
        ),
    ]
