# Generated by Django 5.0.6 on 2024-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0016_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Ping-pong', 'Ping-pong'), ('Football', 'Football'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball')], max_length=20),
        ),
    ]
