# Generated by Django 5.0.6 on 2024-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0025_alter_match_sport_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Ping-pong', 'Ping-pong'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis')], max_length=20),
        ),
    ]
