# Generated by Django 5.0.6 on 2024-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0026_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Handball', 'Handball'), ('Basketball', 'Basketball'), ('Ping-pong', 'Ping-pong'), ('Tennis', 'Tennis'), ('Football', 'Football')], max_length=20),
        ),
    ]
