# Generated by Django 5.0.6 on 2024-06-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0029_alter_match_sport_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Tennis', 'Tennis'), ('Ping-pong', 'Ping-pong'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Handball', 'Handball')], max_length=20),
        ),
    ]
