# Generated by Django 5.0.6 on 2024-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0034_alter_match_sport_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball'), ('Ping-pong', 'Ping-pong'), ('Football', 'Football')], max_length=20),
        ),
    ]
