# Generated by Django 5.0.6 on 2024-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwishApp', '0037_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('Handball', 'Handball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis'), ('Ping-pong', 'Ping-pong'), ('Basketball', 'Basketball')], max_length=20),
        ),
    ]
